import * as React from 'react';
import * as CSSModules from 'react-css-modules';
import { Component } from 'react';

import Popup from '../../common/Popup';
import Input from '../../common/Input';
import Button from '../../common/Button';

export type Props = {
  open: boolean
  onClose: () => void
  onSubmit: (code: string) => void
}

export type StateProps = {
  verificationCode: string
}

class VerificationPopup extends Component<Props, StateProps> {
  constructor(props) {
    super(props);
    this.state = {
      verificationCode: ''
    };

    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState({ verificationCode: e.target.value });
  }

  render() {
    const {
      open,
      onClose,
      onSubmit
    } = this.props;
  
    return (
      <Popup
        title=""
        open={open}
        close={onClose}>
        <div styleName="popup">
          <div styleName="header">
            Two-Step Verification
          </div>
          <div styleName="description">
            Please enter the one-time verification code generated by your authenticator app to confirm signing:
          </div>
          <Input styleName="input" placeholder="Enter code" value={this.state.verificationCode} onChange={this.handleChange}/>
          <Button onClick={() => onSubmit(this.state.verificationCode)}>Submit</Button>
        </div>
      </Popup>
    );
  }
};

const StyledComponent = CSSModules(VerificationPopup, require('./styles.css'));

export default StyledComponent;
