import * as React from 'react';
import * as CSSModules from 'react-css-modules';
import { SFC } from 'react';

import Popup from '../../common/Popup';
import Input from '../../common/Input';
import Button from '../../common/Button';

export type Props = {
  open: boolean
  onClose: () => void
  onSubmit: () => void
}

const VerificationPopup: SFC<Props> = (props) => {
  const {
    open,
    onClose,
    onSubmit
  } = props;

  return (
    <Popup
      title=""
      open={open}
      close={onClose}>
      <div styleName="popup">
        <div styleName="header">
          Two-Step Verification
        </div>
        <div styleName="description">
          Please enter the one-time verification code generated by your authenticator app to confirm signing:
        </div>
        <Input styleName="input" placeholder="Enter code"/>
        <Button onClick={onSubmit}>Submit</Button>
      </div>
    </Popup>
  );
};

const StyledComponent = CSSModules(VerificationPopup, require('./styles.css'));

export default StyledComponent;
