import * as React from 'react';
import * as CSSModules from 'react-css-modules';
import { Component } from 'react';
import { connect } from 'react-redux';
import { browserHistory } from 'react-router';

import Popup from '../../../components/common/Popup';
import Input from '../../../components/common/Input';
import Button from '../../../components/common/Button';

import {
  StateMap as StateProps,
  verifyContract,
  changeVerificationCode,
  resetState
} from '../../../redux/modules/verification/verification';

export type Props = StateProps & DispatchProps & ComponentProps;

export type ComponentProps = {
  isOpen: boolean
  onClose: () => void,
  contractId?: string
}

export type DispatchProps = {
  verifyContract: (code: string) => void
  changeVerificationCode: (payload: { name: string, value: string }) => void
  resetState: () => void
}

class VerificationPopup extends Component<Props, {}> {
  componentWillUnmount() {
    this.props.resetState();
  }

  render() {
    const RedirectPeriod = 1000;

    const {
        verifyContract,
      changeVerificationCode,
      isOpen,
      onClose,
      verificationCode,
      isVerified,
      contractId,
      inProgress
      } = this.props;

    const handleChange = (e) => {
      changeVerificationCode(e.target.value);
    }

    const renderVerificationFormBody = () => (
      <div>
        <div styleName="header">
          Two-Step Verification
          </div>
        <div styleName="description">
          Please enter the one-time verification code generated by your authenticator app to confirm signing:
          </div>
        <Input styleName="input" placeholder="Enter code" value={verificationCode} onChange={handleChange} />
        <Button onClick={() => verifyContract(verificationCode)} spinner={inProgress}>Submit</Button>
      </div>
    );

    const renderSuccessMessage = () => {
      if (contractId) {
        setTimeout(() => {
          browserHistory.push(`/ctr/contracts/${contractId}/`);
        }, RedirectPeriod);
      }

      return (
        <div styleName="verified-section">
          <img styleName="verified-icon" src={require('../../../assets/images/signed.svg')} />
          <span styleName="verified-message">Successfully verified!</span>
        </div>
      )
    };

    return (
      <Popup
        title=""
        open={isOpen}
        close={onClose}>
        <div styleName="popup">
          {isVerified ?
            renderSuccessMessage() :
            renderVerificationFormBody()
          }
        </div>
      </Popup>
    );
  }
};

const StyledComponent = CSSModules(VerificationPopup, require('./styles.css'));

export default connect<StateProps, DispatchProps, ComponentProps>(
  (state) => state.verification.verification,
  {
    verifyContract,
    changeVerificationCode,
    resetState
  }
)(StyledComponent);
